#include "WadNames.h"

// https://github.com/hdc0/Croc-2-mods/blob/master/doc/files.md

std::map<std::string, std::string> wadNames = {
	{"ads.dll", "Audio Playback Library"},
	{"Croc2.exe", "Game executable"},
	{"Loading.bmp", "Loading screen"},
	{"Loading0.bmp", "Loading screen (EN)"},
	{"Loading1.bmp", "Loading screen (FR)"},
	{"Loading2.bmp", "Loading screen (DE)"},
	{"Loading3.bmp", "Loading screen (IT)"},
	{"Loading4.bmp", "Loading screen (ES)"},
	{"Loading5.bmp", "Loading screen (NL)"},
	{"Loading6.bmp", "Loading screen (SE)"},
	{"logos.avi", "Publisher and developer logos"},
	{"Trademarks.bmp", "Splash screen"},
	{"music/CBK2.asf", "Music: \"Cannon Boat Keith\""},
	{"music/CBKLead.asf", "Music: \"CBK Lead Up\""},
	{"music/ChooCave.asf", "Music: \"Choo Cave\""},
	{"music/ChooOut.asf", "Music: \"Choo Outside\""},
	{"music/GTower.asf", "Music: \"Goo Manchoo Tower\""},
	{"music/JBarren1.asf", "Music: \"Barren Wheels One\""},
	{"music/JBarren2.asf", "Music: \"Forest Barren\""},
	{"music/JGoldRock.asf", "Music: \"Gold Rock Race\""},
	{"music/JHub1.asf", "Music: \"Hub Tribe 1\"/\"Hub Tribe 3\""},
	{"music/JHub2.asf", "Music: \"Hub Tribe 2\"/\"Hub Tribe 4\""},
	{"music/JIce2.asf", "Music: \"Ice Land\""},
	{"music/JIceCave.asf", "Music: \"Ice Cave\"/\"Ice Cave One\""},
	{"music/JInca1.asf", "Music: \"Inca Babies One\""},
	{"music/JJungle3.asf", "Music: \"Find The Key\""},
	{"music/JMine2.asf", "Music: \"The Mine\""},
	{"music/JRedAnt1.asf", "Music: \"Red Ant Lair\""},
	{"music/JRedAnt120.asf", "Music: \"Red Ant Bomb\""},
	{"music/JRedAnt25.asf", "Music: \"Red Ant Fast Lair\""},
	{"music/JThiefCave.asf", "Music: \"Thief Cave\""},
	{"music/JThiefJungle.asf", "Music: \"Thief Jungle\""},
	{"music/JTitle.asf", "Music: \"Croc\'s Theme\""},
	{"music/JVenus.asf", "Music: \"Venus\""},
	{"music/JVenusLead.asf", "Music: \"Venus Lead Up\""},
	{"music/KBarren1.asf", "Music: \"Barren Wheels Two\""},
	{"music/KBarren3.asf", "Music: \"Barren Three\""},
	{"music/KCave1.asf", "Music: \"Cave One\""},
	{"music/KCmCave.asf", "Music: \"Caveman Cave One\""},
	{"music/KCmCave2.asf", "Music: \"Caveman Cave Two\""},
	{"music/KDante1.asf", "Music: \"Dante One\""},
	{"music/KDante2.asf", "Music: \"Dante Two\""},
	{"music/KDungeon.asf", "Music: \"Dungeon\""},
	{"music/KFlavio.asf", "Music: \"Flavio\""},
	{"music/KGlide.asf", "Music: \"Glider\""},
	{"music/KIncaCave.asf", "Music: \"Inca Babies Two\""},
	{"music/KJungle3.asf", "Music: \"Jungle Two\""},
	{"music/KLLLarry.asf", "Music: \"Lava Lamp Larry\""},
	{"music/KMasher.asf", "Music: \"Masher\""},
	{"music/KMasherLead.asf", "Music: \"Masher Lead Up\""},
	{"music/KRiverRace.asf", "Music: \"River Race\""},
	{"music/KSnowball.asf", "Music: \"Snowball\""},
	{"music/KSoveena.asf", "Music: \"Soveena\""},
	{"music/KSoveenaLead.asf", "Music: \"Soveena Lead Up\""},
	{"music/KWaterfall.asf", "Music: \"Waterfall\""},
	{"wads/defanim.wad", ""},
	{"wads/fesound.wad", ""},

	{"wads/t0i0m000.wad", "Main menu: main menu"},
	{"wads/t0i0m001.wad", "Main menu: options menu"},
	{"wads/t0i0m002.wad", "Main menu: new game"},
	{"wads/t0i0m003.wad", "Main menu: game over"},
	{"wads/t0i0m004.wad", "Main menu: save slot selection"},
	{"wads/t0i0m006.wad", ""},
	{"wads/t0i0m999.wad", ""},
	{"wads/t0l0m005.wad", "Main menu: credits"},
	{"wads/t0l1m002.dem", "Input data for \"The Village Masher\" demo"},
	{"wads/t0l1m002.wad", "Demo map \"The Village Masher\""},
	{"wads/T0L1M003.DEM", "Input data for \"Burning Down the Forest\" demo"},
	{"wads/t0l1m003.wad", "Demo map \"Burning Down the Forest\""},
	{"wads/T0L1M004.DEM", "Input data for \"Find the Wheels in the Jungle!\" demo"},
	{"wads/t0l1m004.wad", "Demo map \"Find the Wheels in the Jungle!\""},
	{"wads/t0l1m005.dem", "Input data for \"HEY! He Stole my lunch!\" demo"},
	{"wads/t0l1m005.wad", "Demo map \"HEY! He Stole my lunch!\""},
	{"wads/t0l1m006.wad", "Demo map \"Save the Ice Trapped Gobbos!\""},
	{"wads/T0L1M007.DEM", "Input data for \"Find 3 Lost Treasure Chests\" demo"},
	{"wads/t0l1m007.wad", "Demo map \"Find 3 Lost Treasure Chests\""},

	{"wads/t1b1m001.wad", "Soveena The Squid (Part 1)"},
	{"wads/t1b1m002.wad", "Soveena The Squid (Part 2)"},
	{"wads/t1b2m001.wad", "Cannon Boat Keith"},
	{"wads/t1i1m001.a00", ""},
	{"wads/t1i1m001.wad", "Main Game Intro"},
	{"wads/t1i1m002.a00", ""},
	{"wads/t1i1m002.wad", "Sailor Village (New game cutscene)"},
	{"wads/t1i2m001.a00", ""},
	{"wads/t1i2m001.wad", "Cannon Boat Keith (Cutscene)"},
	{"wads/t1l1m001.wad", "Sailor Village"},
	{"wads/t1l1m004.wad", "Swap Meet Pete (Sailor Village)"},
	{"wads/t1l2m001.wad", "Find the Key! Save the Gobbo!"},
	{"wads/t1l2m002.wad", ""},
	{"wads/t1l3m001.wad", "Find 5 Lost Treasure Chests"},
	{"wads/t1l4m001.wad", "Get the Gobbo\'s Sandwich!"},
	{"wads/t1l5m001.wad", "Croc Vs Dantini Boat Race"},
	{"wads/t1l6m001.wad", "Save the Bird from the Thief"},
	{"wads/t1s1m001.wad", "Sailor Tribe - Secret Mine"},

	{"wads/t2b1m001.wad", "Flavio the Thermal Fish"},
	{"wads/t2b2m001.wad", "Lava Lamp Larry"},
	{"wads/t2i2m001.a00", ""},
	{"wads/t2i2m001.wad", "Lava Lamp Larry (Cutscene)"},
	{"wads/t2l1m001.wad", "Cossack Village"},
	{"wads/t2l1m004.wad", "Swap Meet Pete (Cossack Village)"},
	{"wads/t2l2m001.wad", "Save the Ice Trapped Gobbos!"},
	{"wads/t2l3m001.wad", "Chase the Choo Choo Train"},
	{"wads/t2l5m001.wad", "It\'s just Snowball Madness!"},
	{"wads/t2l6m001.wad", "Hang Glider Valley"},
	{"wads/t2l7m001.wad", "KaBooom! It\'s Roger Red Ant"},
	{"wads/t2s1m001.wad", "Cossack Tribe - Secret Ice Cap"},

	{"wads/t3b1m001.wad", "Venus Fly Von-Trappe (Part 1)"},
	{"wads/t3b1m002.wad", "Venus Fly Von-Trappe (Part 2)"},
	{"wads/t3b2m001.wad", "The Village Masher (Part 1)"},
	{"wads/t3b2m002.wad", "The Village Masher (Part 2)"},
	{"wads/t3i1m001.a00", ""},
	{"wads/t3i1m001.wad", "The Village Masher (Cutscene)"},
	{"wads/t3l1m001.wad", "Caveman Village"},
	{"wads/t3l1m004.wad", "Swap Meet Pete (Caveman Village)"},
	{"wads/t3l2m001.wad", "Find the Wheels in the Jungle!"},
	{"wads/t3l3m001.wad", "Find the Wheels in the Mine!"},
	{"wads/t3l4m001.wad", "Race Day at Goldrock"},
	{"wads/t3l5m001.wad", "Climb The Devil\'s Tower"},
	{"wads/t3l7m001.wad", "Save 50 Trapped Gobbos!"},
	{"wads/t3s1m001.wad", "Caveman Tribe - Secret Mine"},

	{"wads/t4b1m001.wad", "Dante\'s Peak"},
	{"wads/t4b2m001.a00", ""},
	{"wads/t4b2m001.wad", "Dante\'s Final Fight"},
	{"wads/t4i1m001.a00", ""},
	{"wads/t4i1m001.wad", "Dante\'s Peak (Cutscene)"},
	{"wads/t4i2m001.a00", ""},
	{"wads/t4i2m001.wad", "Default new map (Ending cutscene)"},
	{"wads/t4l1m001.wad", "Inca Village"},
	{"wads/t4l1m004.wad", "Swap Meet Pete (Inca Village)"},
	{"wads/t4l2m001.wad", "Save 30 Gobbo babies!"},
	{"wads/t4l3m001.wad", "Up the Waterfall"},
	{"wads/t4l5m001.wad", "Bride of the Dungeon of Defright"},
	{"wads/t4l6m001.wad", "Goo Man Chu\'s Tower"},
	{"wads/t4s1m001.wad", "Inca Tribe - Secret Maze"},

	{"wads/t5l2m001.wad", "Secret Sailor Village"},
	{"wads/t5l2m002.wad", "Sailor Secret 1"},
	{"wads/t5l2m003.wad", "Sailor Secret 2"},
	{"wads/t5l2m004.wad", "Sailor Secret 3"},
	{"wads/t5l2m005.wad", "Sailor Secret 4"},
	{"wads/t5l2m006.wad", "Sailor Secret 5"},

	{"wads/t5l3m001.wad", "Secret Cossack Village"},
	{"wads/t5l3m002.wad", "Cossack Secret 1"},
	{"wads/t5l3m003.wad", "Cossack Secret 2"},
	{"wads/t5l3m004.wad", "Cossack Secret 3"},
	{"wads/t5l3m005.wad", "Cossack Secret 4"},
	{"wads/t5l3m006.wad", "Cossack Secret 5"},

	{"wads/t5l4m001.wad", "Secret Caveman Village"},
	{"wads/t5l4m002.wad", "Caveman Secret 1"},
	{"wads/t5l4m003.wad", "Caveman Secret 2"},
	{"wads/t5l4m004.wad", "Caveman Secret 3"},
	{"wads/t5l4m005.wad", "Caveman Secret 4"},
	{"wads/t5l4m006.wad", "Caveman Secret 5"},
};
